### ISSUE TITLE
Noten Modal: Unternoten inkorrekt

### ISSUE THREAD

**Issue by LenMPorath** [greybaron/campus-unbloat#106]
Obwohl sich Bewertungen aus zwei Noten zusammensetzen, wird bei Campus Unbloat bei beiden "Unternoten" exakt das gleiche angegeben. Es wird dort die Gesamtbewertung genommen. Hier zwei Beispiele:

![grafik](https://github.com/user-attachments/assets/12c24f1b-e76c-4aa5-b854-135851b3dc61)
![grafik](https://github.com/user-attachments/assets/90f112ef-f746-4924-8bcd-d0eb42258c2c)

![grafik](https://github.com/user-attachments/assets/3ccd5ba1-e568-4268-8eeb-03c28bd5eaec)
![grafik](https://github.com/user-attachments/assets/c3146f04-4698-4fbf-925d-af59ce5cca9c)

**Comment by greybaron** [comment]
Fixed, bug was introduced API-side during refactoring
