### ISSUE TITLE
Grade Average

### ISSUE THREAD

**Issue by LenMPorath** [greybaron/campus-unbloat#108]
Maybe add a new Grade Average information in either the GradeTile or GradeModal.

**Comment by greybaron** [comment]
Unweighted avg implemented in d7a9ca57e80f1a68f40659fa06ede1dcc617258d. Do you think weighted is beneficial as well? I don’t know about the weighting and implementation is probably too hard anyway (special grades aren't marked as such)

**Comment by LenMPorath** [comment]
Its actually quite precise.

As for the weighting:
In short: SumOfAll(Grade*CPS)/180

Each subject has their respective amount of Credit Points. If you multiply
the grade with the credit points for each subject und divide it by the
total (180) you get the weighted average.

greybaron ***@***.***> schrieb am So., 29. Sept. 2024, 03:59:

**Comment by greybaron** [comment]
Nice, thank you. Implemented in f253decad32542d1b019bb8093584249077ca300. Please close if the value seems accurate

**Comment by greybaron** [comment]
The assumption of 180 CPs leads to wrong results when the user has fewer. 346d35742e285b2583ac66cea38d56648723d43a now assumes using this formula with <180 CPs is also accurate. Close if valid

**Comment by LenMPorath** [comment]
I looked into mock.unbloat.app , and the result is wrong. I forgot to mention, that you have to divide by the total of the credit points you already have. Because we already have 180 CPS, the result for our weighted average is correct, but for peope who dont have 180 CPS in total, its wrong.

In the mock data for example, there is still BASC (12CPS), STDS (4CPS). MEDIT (5CPS) and V3DA (4CPS) missing (= total of 25 CPS). You have to divide by the sum of all already achieved subjects/modules (in this case of the mock by 155).

**Comment by greybaron** [comment]
nice same time

**Comment by LenMPorath** [comment]
lmfao

**Comment by LenMPorath** [comment]
result is valid. push to prod 🚀🚀🚀🚀
