### ISSUE TITLE
Bug: Modals lassen sich nicht mehr öffnen

### ISSUE THREAD

**Issue by LenMPorath** [greybaron/campus-unbloat#19]
On PROD, the following error message gets triggered when opening the calendar-modal. Other modals behave faulty and dont open _after_ triggering the calendar modal.

![image](https://github.com/user-attachments/assets/11ecafe6-ac92-4d7a-a166-c8ed3b2cd8ea)

**Comment by greybaron** [comment]
Fixed in 011e7c73b9b5d1ceed570b1a98f32fb3d2de32a9
