### ISSUE TITLE
tile/modal (day view): customized text when there are no events on certain weekdays

### ISSUE THREAD

**Issue by LenMPorath** [greybaron/campus-unbloat#48]

**Comment by LenMPorath** [comment]
![image](https://github.com/user-attachments/assets/0eb4744c-5e79-49a7-94e8-b1f13cc34828)

Even though the calendar shows the next monday, the bottom text states that "Today" arent any events. 
The text should display (similariyl to the Mensa-Tile title) "morgen", "übermorgen" etc. according to the shown day.

Requirements:
 - The mentioned text should have the following formatting
     - events in the past: "Am DD.MM. fand keine Vorlesung statt"
     - events today: "Heute findet keine Vorlesung statt"
     - events tomorrow: "Morgen findet keine Vorlesung statt"
     - otherwise in the future: "Am DD.MM. findet keine Vorlesung statt"

**Comment by olech2412** [comment]
i think we need a meeting for this. Please DM me

**Comment by LenMPorath** [comment]
who are you

Am Mo., 5. Aug. 2024 um 12:19 Uhr schrieb Ole Einar Christoph <
***@***.***>:
